cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'atuin'
brew 'cloudflared'
brew 'imagemagick'
brew 'postgresql@17'
brew 'redis'
brew 'ruby-build'
brew 'spaceman-diff'
brew 'spark'
brew 'stripe/stripe-cli/stripe'
brew 'stripe/stripe-mock/stripe-mock'
brew 'wget'
brew 'yt-dlp'

cask 'airtable'
cask 'arq'
cask 'ghostty'
cask 'iina'
cask 'messenger'
cask 'notion-calendar'
cask 'plex'
cask 'quicklook-video'
cask 'sonos'
cask 'steam'
cask 'telegram'
cask 'transmission'
cask 'raycast'
cask 'whatsapp'
cask 'visual-studio-code'
cask 'vlc'
cask 'zed'
