cask_args appdir: '/Applications'

tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "localsend/localsend"

brew "docker-compose", link: false
brew "exiftool"
brew "gh"
brew "git"
brew "git-extras"
brew "mysql"
brew "node@18"
brew "node@20"
brew "nut"
brew "python@3.9"
brew "ruby-install"
brew "spark"
brew "wget"
brew "yarn"
brew "yt-dlp"

cask "appzapper"
cask "balenaetcher"
cask "clicker-for-youtube"
cask "cyberduck"
cask "discord"
cask "docker"
cask "font-hack"
cask "gdisk"
cask "github"
cask "google-chrome"
cask "iterm2"
cask "keyboard-cleaner"
cask "localsend"
cask "mark-text"
cask "messenger"
cask "omnidisksweeper"
cask "postman"
cask "raycast"
cask "slack"
cask "spotify"
cask "ultimaker-cura"
cask "visual-studio-code"
cask "vlc"
cask "warp"
cask "xee"
